# Generated by Django 2.2.7 on 2020-08-11 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_limu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='fail_text',
            field=models.TextField(blank=True, default='Hurray you have failed', help_text='Displayed if user fails.', verbose_name='Fail Text'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='level',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=20),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='success_text',
            field=models.TextField(blank=True, default='Hurray you have passed', help_text='Displayed if user passes.', verbose_name='Success Text'),
        ),
    ]
