# Generated by Django 2.2.7 on 2020-09-17 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_limu', '0002_auto_20200811_2124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='is_correct',
        ),
        migrations.AddField(
            model_name='choice',
            name='correct_choice',
            field=models.BooleanField(default=False),
        ),
    ]
