# Generated by Django 2.2.7 on 2020-11-22 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_limu', '0002_auto_20201122_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='position',
            field=models.CharField(choices=[('a', 'a'), ('b', 'b'), ('c', 'c'), ('d', 'd')], max_length=50),
        ),
    ]
