# Generated by Django 2.2.7 on 2020-09-17 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('E_limu', '0003_auto_20200917_2327'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='correct_choice',
            new_name='is_correct',
        ),
    ]
