# Generated by Django 2.2.7 on 2021-02-03 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_limu', '0003_auto_20201122_2055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='instructor',
        ),
        migrations.AlterField(
            model_name='subject',
            name='title',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
