# Generated by Django 2.2.7 on 2020-09-18 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_limu', '0004_auto_20200917_2329'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choice',
            options={},
        ),
        migrations.AlterField(
            model_name='choice',
            name='choice',
            field=models.CharField(max_length=100, verbose_name='Choice'),
        ),
        migrations.AlterUniqueTogether(
            name='choice',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='choice',
            name='position',
        ),
    ]
