# Generated by Django 2.2.7 on 2021-02-03 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_limu', '0004_auto_20210203_0044'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
