# Generated by Django 2.2.7 on 2020-09-18 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_limu', '0005_auto_20200918_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='choice',
            field=models.CharField(max_length=100, verbose_name='choice_types'),
        ),
    ]
