# Generated by Django 2.2.7 on 2020-09-18 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('E_limu', '0009_auto_20200918_2213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='choice',
        ),
    ]
