# Generated by Django 2.2.7 on 2020-09-18 23:44

import E_learning_API.E_limu.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_limu', '0011_choice_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='choice_types',
            field=models.CharField(default='a', max_length=100, verbose_name=E_learning_API.E_limu.models.Choice.choice_types),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='choice',
            name='choice',
            field=models.CharField(max_length=100),
        ),
    ]
