# Generated by Django 2.2.7 on 2020-09-19 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_limu', '0013_auto_20200918_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='choice_types',
            field=models.CharField(max_length=100),
        ),
    ]
