# Generated by Django 2.2.7 on 2020-11-22 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_limu', '0014_auto_20200919_0347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='choice_types',
        ),
        migrations.AlterField(
            model_name='choice',
            name='choice',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
