# Generated by Django 2.2.7 on 2020-11-22 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_limu', '0015_auto_20201122_0136'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='choice_types',
            field=models.CharField(default='a', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='choice',
            name='choice',
            field=models.CharField(default='bmn', max_length=100),
            preserve_default=False,
        ),
    ]
